version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    volumes:
      - postgres:/data/postgres
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5435:5432"
    env_file:
      - ./Database/.database.env
    networks:
      - notification-system
    restart: unless-stopped
  notification-producer:
    container_name: notification-producer
    build:
      dockerfile: Dockerfile
      context: ./Producer
    volumes:
      - .:/usr/app
    env_file:
      - ./Producer/.env
    ports:
      - 8000:8000
    networks:
      - notification-system
    depends_on:
      - postgres
    restart: unless-stopped
  notification-consumer:
    container_name: notification-consumer
    build:
      dockerfile: Dockerfile
      context: ./Consumer
    volumes:
      - .:/usr/app
    env_file:
      - ./Consumer/.env
    ports:
      - 8001:8001
    networks:
      - notification-system
    depends_on:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    env_file:
      - ./Rabbit/.rabbit.env
    networks:
      - notification-system
    restart: unless-stopped
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./Grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - notification-system
    restart: unless-stopped
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - notification-system
    restart: unless-stopped

networks:
  notification-system:
    driver: bridge

volumes:
  notification-producer:
    driver: local
  notification-consumer:
    driver: local
  rabbitmq:
    driver: local
  grafana:
    driver: local
  prometheus:
    driver: local
  postgres:
    driver: local
